### ISSUE TITLE
Mojibake, character encoding and locale problem

### ISSUE THREAD

**Issue by neo954** [ways/fingr#1]
I got the following outputs. It seems `ISO8859-1` encoding was used for the outputs of the finger server. As you can see, there are Mojibake/garbage characters as shown.
```
$ finger beijing@graph.no
                      -= Meteogram for �M-^LM-^W京��M-^B, 100051, 中�M-^[� =-                       
 'C                                                                   Rain (mm) 
 23                                                                   
 21=--^^^                                                      ---=-- 
 19      ^^^                                             =--^^^       
 17         ^^^                                    ======             
 15            ^^^^^^                           ===                   
 13                  ^^^=--                                           
 11                        ---               ^^^                      
  9                           ------^^^                               
  7                                    =--^^^                         
  5                                                                   
   _17_18_19 20 21 22 23 29/04 02 03 04 05_06_07_08_09_10_11_12_13_14 Hour
    
    SW SW  S  S SW SW  W SW SW  W NW NW  N  N NW NW NW NW NW NW NW NW Wind dir.
     6  5  5  5  3  3  2  1  1  2  2  2  2  2  3  4  7  6  6  6  7  8 Wind(m/s)

Legend left axis:   - Sunny   ^ Scattered   = Clouded   =V= Thunder   # Fog
Legend right axis:  | Rain    ! Sleet       * Snow
[Tip: You can ask for wind chill. Add ¤ in front of location name.]
```
It seems `UTF-8` characters were incorrectly converted to `ISO8859-1`. Characters, `京`, `100051`, and `中`, are actually correctly displayed. I assume the correct characters should be `北京市, 100051, 中国`.

BTW, `en_US.UTF-8` was used at the client side.
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by neo954** [comment]
I would suggest limit the location name to pure ASCII characters.

**Comment by ways** [comment]
Thanks. I'll look into it.

Limiting to ascii would impact lots of names, making it impossible to show i.e.:

```
$ finger bliksvær@graph.no
           -= Meteogram for Bliksvær, Bodø, Nordland, 8096, Norge =-            

```

**Comment by neo954** [comment]
Yes, you are right. It would affect lots of names. But the previous version (https://github.com/ways/pyyrascii) keep all the location name to ASCII characters.

So, here is the real question. **Whether use English for all location names, or use local names for all the locations.** There is no right or wrong for this kind of thing. It is just choice of software design. It is your philosophy of software design.

Option A - Use English for location names.
Pros:
* Limited all display characters to ASCII
* Only one language, English, is used in the software user interface.
Cons:
* No internationalization support at all.

Option B - Use local name for location names.
Pros:
* The local names might be get from the under-layer API, thus no conversion need.
Cons:
* Mixed English and other language makes the software user interface confusion.
* Need full support of Unicode and internationalization. Which needs more coding and add complexity of the software.

I would like to choose option A, and keep things simple and straight forward.

**Comment by neo954** [comment]
I will give some test cases as examples and show the complexity of different language and internationalization support.

`finger Beijing@graph.no`
The local language is Simplified Chinese. Thus, East-Asian language support. Each Chinese character occupies double width for display. Need special treatment for calculate string length and display space.
`finger Tokyo@graph.no`
Japanese language, same as above.
`finger Seoul@graph.no`
Korean language, same as above.
`finger Riyadh@graph.no`
Riyadh is the capital of Saudi Arabia. Thus, Arabic language. And Arabic language is written from right to left. When mix right-to-left script (Arabic) and left-to-right script (English), bidirectional text support is need.

The list can go on. But I think I made my point. Software internationalization support is very complex.

**Comment by ways** [comment]
Merged.

**Comment by ways** [comment]
I'm not sure that was enough. Don't have time to look into it right now, but I deployed code and flushed redis, weather cache. Some names looks like before, some are definitely English now, but some give weird artifacts. I probably have to check if it's utf-8 all the way, or some conversion needed.

`$ finger bodø@graph.no   
                -= Meteogram for Bodø, Nordland, 8005, Norway =-                
`

`$ finger beijing@graph.no
                   -= Meteogram for Beijing, 100051, China =-                   
`

`$ finger østerås,norge~160@graph.no
                                                    -= Meteogram for �M-^Xsterås, Bærum, Viken, 1361, Norway =-                                                     
`

**Comment by pau4o** [comment]
Cyrillic location names are displayed properly with merged fix
