### ISSUE TITLE
Question: is there a modifier to display colored output with unicode symbols?

### ISSUE THREAD

**Issue by poetaman** [ways/fingr#3]
How to get the effect of colors and unicode symbols like in your screenshot here:

![](https://0p.no/_images/finger3.png)

Source webpage: https://0p.no/2014/12/13/graph_no___weather_forecast_via_finger.html

**Comment by ways** [comment]
There's a link next to the image, pointing to [https://github.com/ways/pyyrascii/blob/master/graph.sh](https://github.com/ways/pyyrascii/blob/master/graph.sh). So it's a script you run locally that fetches the weather via finger, and replaces symbols with unicode. I never used anything but ASCII in the service it self, to make sure it's compatible with all platforms.

I don't know if the script still works, I haven't used it in years.
