### ISSUE TITLE
Wind speed in Beaufort scale

### ISSUE THREAD

**Issue by sotpapathe** [ways/fingr#5]
Would it be possible to add a switch to show the wind speed in the [Beaufort scale](https://en.wikipedia.org/wiki/Beaufort_scale) and everything else in metric units? This is how weather is commonly reported in Greece for example.

**Comment by ways** [comment]
https://github.com/BrunoASNascimento/beaufort-scale seems to fit this problem.

**Comment by sotpapathe** [comment]
I think the numerical Beaufort scale is used much more in practice, that is, 0 instead of "Calm", 1 instead of "Light air", etc.

I can prepare a PR one of these days if that's OK with you. Any suggestion on what symbol to use in the finger request to change the units to Beaufort?

**Comment by ways** [comment]
Merged. Waiting for testing and deploy to main service.

**Comment by ways** [comment]
I've prepared the app to run as a container, added more unit tests and cleaned up a bit. But the beaufort conversion doesn't seem to do anything. Care to have a look? Check readme for easiest way to run the app now.

**Comment by sotpapathe** [comment]
Sure, I'll have a look in the next couple of weeks. Thanks for making it easy to run using docker!

**Comment by ways** [comment]
Nice. I can't verify the result, but looks better to me. Will test it for a while.

**Comment by sotpapathe** [comment]
It worked fine locally. The problem was that the variable used to print the wind speed was set before the unit conversion happened.

**Comment by sotpapathe** [comment]
Looks great, thanks!
